Modification du modèle du dossier d'estimation
yanport/yanport-api-doc pull request #43
Opened 2023-08-30 13:44 UTC by mjore

https://github.com/yanport/backlog/issues/1764

2023-08-30 15:50 UTC, gnieutin requested changes

2023-08-30 15:50 UTC, gnieutin commented on src/components/schemas/CommercialZone.yaml
> +      format: int64
:sparkles: **suggestion** (non-blocking) : 
```suggestion
      type: integer
      format: int64
```

2023-08-30 15:50 UTC, gnieutin commented on src/components/schemas/Product.yaml
> +  onBoarded:
:thinking: **thought** : il me semble que @clardeur avait dit de ne pas le mettre (dans Slack)

2023-08-30 15:50 UTC, gnieutin commented on src/components/schemas/ProductDealer.yaml
>        type: number
:sparkles: **suggestion** (non-blocking) : type integer (Cf. https://spec.openapis.org/oas/v3.1.0#data-types)

2023-08-31 05:56 UTC, mjore commented on src/components/schemas/Product.yaml
> +  onBoarded:
En effet, j'ai enlever le champ `onBoarded` présent sur le modèle `User` mais pas ici.

2023-08-31 07:46 UTC, gnieutin approved these changes

2023-08-31 08:01 UTC, merged