Industrialisation détection d'anomalies : valeur par défaut dans l'API
yanport/yanport-api-doc pull request #69
Opened 2024-04-11 09:41 UTC by Quentin18

feat: update anomaly params for properties

Refs: https://github.com/yanport/backlog/issues/1689

2024-04-15 16:40 UTC, gnieutin requested changes

2024-04-15 16:40 UTC, gnieutin commented on src/components/parameters/anomalyLevelMax.yaml
> +description: Niveau d'anomalie maximal
:+1: **praise** :

2024-04-15 16:40 UTC, gnieutin commented on src/components/schemas/Anomaly.yaml
> +    description: Valeur d'anomalie (inconnu = -1, sûr = 0, inhabituel = 1, suspect = 2, anormal = 3)
:sparkles: **suggestion** (non-blocking) : pour ma part j'aurais fait le mapping en reprenant le nom des clés et non "en bon français". Ici il y a un mapping mental supplémentaire (la traduction)

2024-04-15 16:40 UTC, gnieutin commented on src/paths/properties@evolution@stock.yaml
> +    pour plus de détails.
:magic_wand: **chore** : description différentes des autre : il manque le "voir les valeurs possibles..."

2024-04-15 16:40 UTC, gnieutin commented on src/paths/properties@stats@group-by-{groupBy}-and-{subGroupBy}.yaml
> +    pour plus de détails.
:magic_wand: **chore** : description incomplète

2024-04-15 16:40 UTC, gnieutin commented on src/paths/properties@stats@group-by-{groupBy}.yaml
> +
:magic_wand: **chore** : description incomplète

2024-04-15 16:40 UTC, gnieutin commented on src/paths/similar-properties.yaml
> +    - $ref: ../components/parameters/active.yaml
:+1: **praise** :

2024-04-15 17:46 UTC, Quentin18 commented on src/components/schemas/Anomaly.yaml
> +    description: Valeur d'anomalie (inconnu = -1, sûr = 0, inhabituel = 1, suspect = 2, anormal = 3)
J'ai remplacé par le nom des clés

2024-04-15 17:47 UTC, Quentin18 commented on src/paths/properties@evolution@stock.yaml
> +    pour plus de détails.
J'ai oublié de mettre à jour pour ce endpoint. C'est fixé.

2024-04-15 17:47 UTC, Quentin18 commented on src/paths/properties@stats@group-by-{groupBy}-and-{subGroupBy}.yaml
> +    pour plus de détails.
J'ai oublié de mettre à jour pour ce endpoint. C'est fixé.

2024-04-15 17:47 UTC, Quentin18 commented on src/paths/properties@stats@group-by-{groupBy}.yaml
> +
J'ai oublié de mettre à jour pour ce endpoint. C'est fixé.

2024-04-16 09:06 UTC, gnieutin submitted a review, later dismissed

2024-04-16 09:22 UTC, Quentin18 commented on src/components/parameters/greenhouseGasConsumptionDiagnosisLetter.yaml
> +  example: D
Fait

2024-04-16 09:50 UTC, gnieutin approved these changes

2024-04-16 09:51 UTC, merged