Développement Endpoint evolution - calculs de croissance
yanport/yanport-api-doc pull request #94
Opened 2024-12-20 13:46 UTC by Quentin18

feat: add growth and reliability models

2024-12-26 23:14 UTC, gnieutin commented on src/components/schemas/CountAgg.yaml
> +    description: Nombre d'observations
:thinking: **thought** : avoir 2 champs dont la description est la même va faire que le client va se demander la différence entre les 2 ^^ Il faut soit être plus explicite soit plus évasif ici mais pas avoir la même description

2024-12-26 23:14 UTC, gnieutin commented on src/components/schemas/Percentiles.yaml
> +      format: double
:question: **question** : on obtient le même résultat qu'avant dans la doc avec çà ?

2025-01-02 14:33 UTC, Quentin18 commented on src/components/schemas/Percentiles.yaml
> +      format: double
Actuellement, la documentation du modèle `Percentiles` est imcomplète. On a juste un exemple pour que ça rende bien dans les exemples de réponse, mais on a pas la définition du modèle exact. Le `additionalProperties` permet de représenter la HashMap des percentiles (voir https://swagger.io/docs/specification/v3_0/data-models/dictionaries/).

2025-01-02 14:41 UTC, Quentin18 commented on src/components/schemas/CountAgg.yaml
> +    description: Nombre d'observations
Effectivement la description n'était pas bonne. Je l'ai changé.

2025-01-14 11:04 UTC, gnieutin requested changes

2025-01-14 11:04 UTC, gnieutin commented on src/components/schemas/CountAgg.yaml
> +    description: Indicateurs de croissance du nombre d'observations
:thinking: **thought** : Pour le coup, c'est des indicateurs de croissance de la valeur et pas du nombre d'observations puisque le nombre d'observation c'est le champs `count`. Pour éviter un quiproquo, je te propose ça, même si c'est moins concis, c'est + précis. A adapter si tu trouves mieux mais voilà l'idée : 
```suggestion
    description: Indicateurs de croissance de la valeur, comparée aux valeurs précédentes (uniquement renseignée lors d'une requête d'évolution)
```

2025-01-14 13:06 UTC, gnieutin requested changes

2025-01-14 13:06 UTC, gnieutin commented on src/components/schemas/Average.yaml
> +    description: Indicateurs de croissance de la moyenne
:magic_wand: **chore** : ajouté l'info sur "quand" est renseigné cette valeur

2025-01-14 14:54 UTC, Quentin18 commented on src/components/schemas/Average.yaml
> +    description: Indicateurs de croissance de la moyenne
Fait

2025-01-14 15:24 UTC, gnieutin approved these changes

2025-01-15 12:36 UTC, merged